import webapp2
import handlers as h
import toys as t
import constants

app = webapp2.WSGIApplication([('/', h.MainpageHandler),
                               ('/tmi/?', h.MainpageHandler),
                               ('/about/?', h.AboutHandler),
                               ('/signup/?', h.SignupHandler),
                               ('/login/?', h.LoginHandler),
                               ('/logout/?', h.LogoutHandler),
                               ('/profile/?', h.ProfileHandler),
                               ('/img', h.ImageHandler),
                               ('/postactivity/?', h.PostActivityHandler),
                               ('/inspostactivity/?', h.InsPostActivityHandler),
                               ('/postbatchactivity/?', h.PostBatchActivityHandler),
                               ('/posttimedactivity/?', h.PostTimedActivityHandler),
                               ('/postbatchtimedactivity/?', h.PostBatchTimedActivityHandler),
                               ('/postexpense/?', h.PostExpenseHandler),
                               ('/postbatchexpense/?', h.PostBatchExpenseHandler),
                               ('/categorizeexpense/?', h.CategorizeExpenseHandler),
                               ('/posttravel/?', h.PostTravelHandler),
                               ('/postmeal/?', h.PostMealHandler),
                               ('/postbatchmeal/?', h.PostBatchMealHandler),
                               ('/postbook/?', h.PostBookHandler),
                               ('/postgame/?', h.PostGameHandler),
                               ('/postmessage/?', h.PostUserMessageHandler),
                               ('/postguestmessage/?', h.PostGuestMessageHandler),
                               ('/postimage/?', h.PostImageHandler),
                               ('/panel/?', h.PanelHandler),
                               ('/activities/?', h.PresentActivityHandler),
                               ('/timedactivities/?', h.PresentTimedActivityHandler),
                               #('/library', h.LibraryHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/expenses/?', h.PresentExpenseHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/library/?', h.LibraryHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/gallery/?', h.ImageGalleryHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/blog/' + r'([0-9]+)/edit', h.Blog_EditPostHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/blog/' + r'([0-9]+)/?', h.Blog_ShowSinglePostHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/blog/?', h.Blog_ShowPostsHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/blog/newpost/?', h.Blog_NewPostHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})' + '/blog/panel/?', h.Blog_PanelHandler),
                               ('/blog_change_default_categories', h.Blog_ShuffleCategoriesHandler),
                               ('/hack/?', h.HackHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})/public/?', h.PublicUserpageHandler),
                               ('/u/' + r'([a-zA-Z0-9_-]{4,20})/?', h.UserpageHandler),
                               ('/toys/simplechart/?', t.SimpleChartHandler),
                               ('/toys/' + r'([a-zA-Z0-9_-]{4,20})/?', t.ToyUserHandler),
                               ('/toys/?', t.ToypageHandler),],
                               debug = False)